dist: xenial
notifications:
  email: false
sudo: required
language: python
python:
  - "3.7"
cache:
  pip: true
addons:
  apt:
    packages:
      - xvfb
  chrome: stable
  # https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html
  firefox: "57.0"
services:
  - xvfb
before_install:
  - set +e
  - sudo service xvfb stop
  - sudo sed -i 's/1024x768/1680x1050/g' /etc/systemd/system/xvfb.service
  - sudo service xvfb start 
install:
  - pip install -r requirements.txt
before_script:
  - python mysite/manage.py migrate
  # moved hire due to time to run
  - python mysite/manage.py runserver &
  # Keep in mind Xenial Chrome Stable version and Chromedriver version
  - wget http://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver
  
  # Install Firefox (Gecko) driver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/geckodriver
  
script:
  - robot -d ./results tests/

after_script:
  - file results/selenium-screenshot-1.png

