notifications:
  email: false

language: python
python:
  - "3.7"
dist: xenial
addons:
  apt:
    packages:
      - xvfb
  chrome: stable
services:
  - xvfb
sudo: required
cache:
  pip: true
install:
  - pip install -r requirements.txt
before_script:
  - echo $PATH
  - python robotix/manage.py migrate
  # moved hire due to time to run
  - python robotix/manage.py runserver &
  # Keep in mind Xenial Chrome Stable version and Chromedriver version
  - wget http://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver
  
  # Install Firefox (Gecko) driver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/geckodriver
  
script:
  - robot tests/
