notifications:
  email: false

language: python
python:
  - "3.7"
dist: xenial
addons:
  apt:
    packages:
      - xvfb
      - google-chrome-stable
  chrome: stable
services:
  - xvfb
sudo: true
cache:
  pip: true
# before_install:
  # start your web application and listen on `localhost`
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - pip install -r requirements.txt
  # - webdrivermanager chrome --linkpath /usr/local/bin `
  # - apt-get install xvfb
  - export DISPLAY=':99.0'
  # - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script: 
  - xvfb-run --server-args="-screen 0, 1920x1080x24" make test  #  > /dev/null 2>&1 &
  - robot tests/
