notifications:
  email: false

language: python
python:
  - "3.7"
dist: xenial
addons:
  apt:
    packages:
      - xvfb
  chrome: stable
services:
  - xvfb
sudo: required
cache:
  pip: true
install:
  - pip install -r requirements.txt
before_script:
  - python robotix/manage.py migrate
  # moved hire due to time to run
  - python robotix/manage.py runserver &
  # google chrome standalone driver
  # Keep in mind Xenial Chrome Stable version and Chromedriver version
  # - wget http://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  # - unzip chromedriver_linux64.zip
  # - sudo mv chromedriver /usr/local/bin
  # - sudo chmod a+x /usr/local/bin/chromedriver
  - webdrivermanager firefox chrome --linkpath /usr/local/bin
script:
  - robot tests/
